export default {
	GET_VIDEOS: 'GET_VIDEOS',
	GET_EFFECTS: 'GET_EFFECTS',
	GET_CLIPS: 'GET_CLIPS',
	GET_VIDEOS_ERROR: 'GET_VIDEOS_ERROR',
	GET_EFFECTS_ERROR: 'GET_EFFECTS_ERROR',
	GET_CLIPS_ERROR: 'GET_CLIPS_ERROR',
	ADD_VIDEO: 'ADD_VIDEO',
	ADD_VIDEO_ERROR: 'ADD_VIDEO_ERROR',
	ADD_CLIP: 'ADD_CLIP',
	ADD_CLIP_ERROR: 'ADD_CLIP_ERROR'
};
