const constants = {
	GET_FRAMES: 'GET_FRAMES',
	GET_FRAMES_ERROR: 'GET_FRAMES_ERROR',

	GET_VIDEOS: 'GET_VIDEOS',
	GET_VIDEOS_ERROR: 'GET_VIDEOS_ERROR',

	GET_EFFECTS: 'GET_EFFECTS',
	GET_EFFECTS_ERROR: 'GET_EFFECTS_ERROR',

	GET_CLIPS: 'GET_CLIPS',
	GET_CLIPS_ERROR: 'GET_CLIPS_ERROR',

	ADD_VIDEO: 'ADD_VIDEO',
	ADD_VIDEO_ERROR: 'ADD_VIDEO_ERROR',

	ADD_CLIP: 'ADD_CLIP',
	ADD_CLIP_ERROR: 'ADD_CLIP_ERROR',

	ADD_PROJECT: 'ADD_PROJECT',
	ADD_PROJECT_ERROR: 'ADD_PROJECT_ERROR',

	ADD_TIMELINE: 'ADD_TIMELINE',
	ADD_TIMELINE_ERROR: 'ADD_TIMELINE_ERROR',

	ADD_EFFECT: 'ADD_EFFECT',
	ADD_EFFECT_ERROR: 'ADD_EFFECT_ERROR',
};


export default constants;
