const constants = {
	GET_TIMELINE: 'GET_TIMELINE',
	GET_TIMELINE_ERROR: 'GET_TIMELINE_ERROR',

	GET_VIDEOS: 'GET_VIDEOS',
	GET_VIDEOS_ERROR: 'GET_VIDEOS_ERROR',

	GET_EFFECTS: 'GET_EFFECTS',
	GET_EFFECTS_ERROR: 'GET_EFFECTS_ERROR',

	GET_CLIPS: 'GET_CLIPS',
	GET_CLIPS_ERROR: 'GET_CLIPS_ERROR',

	ADD_VIDEO: 'ADD_VIDEO',
	ADD_VIDEO_ERROR: 'ADD_VIDEO_ERROR',
}

export default constants;
